package modelo;
// Generated 01-03-2019 05:54:03 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.math.RoundingMode;




/**
 * CargoAbono generated by hbm2java
 */
public class CargoAbono  implements java.io.Serializable {


     private int id;
     private Cuenta cuenta;
     private Partida partida;
     private Float monto;
     private String operacion;

    public CargoAbono() {
    }

	
    public CargoAbono(int id) {
        this.id = id;
    }
    
    public CargoAbono(Cuenta cuenta, Float monto, String operacion) {
       this.cuenta = cuenta;
       this.monto = monto;
       this.operacion = operacion;
    }
    
    public CargoAbono(Cuenta cuenta, Partida partida, Float monto, String operacion) {
       this.cuenta = cuenta;
       this.partida = partida;
       this.monto = monto;
       this.operacion = operacion;
    }
    
    public CargoAbono(int id, Cuenta cuenta, Partida partida, Float monto, String operacion) {
       this.id = id;
       this.cuenta = cuenta;
       this.partida = partida;
       this.monto = monto;
       this.operacion = operacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public Float getMonto() {
        return new BigDecimal(this.monto).setScale(2, RoundingMode.HALF_UP).floatValue();
    }
    
    public void setMonto(Float monto) {
        this.monto = new BigDecimal(monto).setScale(2, RoundingMode.HALF_UP).floatValue();
    }
    public String getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }
}


