package modelo;
// Generated 12-26-2017 08:35:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *CargoAbonos generated by hbm2java
 */
public class CargoAbono  implements java.io.Serializable {

     private int id;
     private Cuenta cuenta;
     private Partida partida;
     private Float monto;
     private String operacion;
     private Set parciales = new HashSet(0);

    public CargoAbono() {
	   
	}

	
    public CargoAbono(int id) {
        this.id = id;
    }
    
    public CargoAbono(Cuenta cuenta, Partida partida, Float monto, String operacion) {
       this.cuenta = cuenta;
       this.partida = partida;
       this.monto = monto;
       this.operacion = operacion;
    }
    
    public CargoAbono(Cuenta cuenta, Partida partida, Float monto, String operacion, Set parciales) {
       this.cuenta = cuenta;
       this.partida = partida;
       this.monto = monto;
       this.operacion = operacion;
       this.parciales = parciales;
    }
    
    public CargoAbono(int id, Cuenta cuenta, Partida partida, Float monto, String operacion, Set parciales) {
       this.id = id;
       this.cuenta = cuenta;
       this.partida = partida;
       this.monto = monto;
       this.operacion = operacion;
       this.parciales = parciales;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public Float getMonto() {
        return this.monto;
    }
    
    public void setMonto(Float monto) {
        this.monto = monto;
    }
    public String getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }
    public Set getParciales() {
        return this.parciales;
    }
    
    public void setParciales(Set parciales) {
        this.parciales = parciales;
    }

	
}


