package modelo;
// Generated 12-26-2017 08:35:28 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

/**
 *Cuentas generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private int id;
     private Cuenta cuenta;//Este atributo hace referencia a la cuenta padre
     private String codigo;
     private String nombre;
     private String descripcion;
     private String tipo;
     private Set parciales = new HashSet(0);
     private Set cuentas  = new HashSet(0);
     private Set cargosAbonos = new HashSet(0);
     private List<Cuenta> cuentasHijas = new ArrayList<Cuenta>();
    public Cuenta() {
    }

	
    public Cuenta(int id) {
        this.id = id;
    }
    
    public Cuenta(String codigo) {
        this.codigo = codigo;
    }
    
    public Cuenta(Cuenta cuenta, String codigo, String nombre, String descripcion, String tipo) {
       this.cuenta = cuenta;
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
    }
    
    public Cuenta(Cuenta cuenta, String codigo, String nombre, String descripcion, String tipo, Set parciales, Set cuentas, Set cargosAbonos) {
       this.cuenta = cuenta;
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.parciales = parciales;
       this.cuentas = cuentas;
       this.cargosAbonos = cargosAbonos;
    }
    
    public Cuenta(int id,Cuenta cuenta, String codigo, String nombre, String descripcion, String tipo, Set parciales, Set cuentas, Set cargosAbonos) {
       this.id = id;
       this.cuenta = cuenta;
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.parciales = parciales;
       this.cuentas = cuentas;
       this.cargosAbonos = cargosAbonos;
    }

   @Override
   public int hashCode() {
	  int hash = 3;
	  hash = 53 * hash + this.id;
	  return hash;
   }

   @Override
   public boolean equals(Object obj) {
	  if (this == obj) {
		 return true;
	  }
	  if (obj == null) {
		 return false;
	  }
	  if (getClass() != obj.getClass()) {
		 return false;
	  }
	  final Cuenta other = (Cuenta) obj;
	  if (this.id != other.id) {
		 return false;
	  }
	  return true;
   }

   
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getParciales() {
        return this.parciales;
    }
    
    public void setParciales(Set parciales) {
        this.parciales = parciales;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }
    public Set getCargosAbonos() {
        return this.cargosAbonos;
    }
    
    public void setCargosAbonos(Set cargosAbonos) {
        this.cargosAbonos = cargosAbonos;
    }

    public List<Cuenta> getCuentasHijas() {
        return cuentasHijas;
    }

    public void setCuentasHijas(List<Cuenta> cuentasHijas) {
        this.cuentasHijas = cuentasHijas;
    }
    
    



}


