package modelo;
// Generated 12-26-2017 08:35:28 PM by Hibernate Tools 4.3.1

/**
 * Parcial generated by hbm2java
 */
public class Parcial implements java.io.Serializable {

    private int id;
    private CargoAbono cargoAbono;
    private Cuenta cuenta;
    private Float monto;

    public Parcial() {
    }

    public Parcial(int id) {
        this.id = id;
    }

    public Parcial(CargoAbono cargoAbono, Cuenta cuenta, Float monto) {
        this.cargoAbono = cargoAbono;
        this.cuenta = cuenta;
        this.monto = monto;
    }
    
    public Parcial(int id, CargoAbono cargoAbono, Cuenta cuenta, Float monto) {
        this.id = id;
        this.cargoAbono = cargoAbono;
        this.cuenta = cuenta;
        this.monto = monto;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public CargoAbono getCargoAbono() {
        return this.cargoAbono;
    }

    public void setCargoAbono(CargoAbono cargoAbono) {
        this.cargoAbono = cargoAbono;
    }

    public Cuenta getCuenta() {
        return this.cuenta;
    }

    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }

    public Float getMonto() {
        return this.monto;
    }

    public void setMonto(Float monto) {
        this.monto = monto;
    }

}
