package modelo;
// Generated 01-03-2019 05:54:03 PM by Hibernate Tools 4.3.1

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidas generated by hbm2java
 */
public class Partida implements java.io.Serializable {

   private int id;
   private Periodo periodo;
   private Date fecha;
   private String descripcion;
   private Integer contador;//Numero de Partida
   private Set cargosAbonos = new HashSet(0);

   public Partida() {
   }

   public Partida(int id) {
      this.id = id;
   }

   public Partida(int id, int contador) {
      this.id = id;
      this.contador = contador;
   }

   public Partida(Date fecha, String descripcion, Integer contador) {
      this.fecha = fecha;
      this.descripcion = descripcion;
      this.contador = contador;
   }

   public Partida(Date fecha, String descripcion, Integer contador, Set cargosAbonos) {
      this.fecha = fecha;
      this.descripcion = descripcion;
      this.contador = contador;
      this.cargosAbonos = cargosAbonos;
   }

   public Partida(int id, Periodo periodo, Date fecha, String descripcion, int contador, Set cargosAbonos) {
      this.id = id;
      this.periodo = periodo;
      this.fecha = fecha;
      this.descripcion = descripcion;
      this.contador = contador;
      this.cargosAbonos = cargosAbonos;
   }

   public int getId() {
      return this.id;
   }

   public void setId(int id) {
      this.id = id;
   }

   public Periodo getPeriodo() {
      return this.periodo;
   }

   public void setPeriodo(Periodo periodo) {
      this.periodo = periodo;
   }

   public Date getFecha() {
      return this.fecha;
   }

   public void setFecha(Date fecha) {
      this.fecha = fecha;
   }
   
   public void setFecha(String fecha) {
      //cadenas vacias o nulas indicaran la fecha actual
      //a la hora de insertar o modificar
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
      try {
         if (fecha == null || "".equals(fecha)) {
	//fecha actual
	Calendar calendario = new GregorianCalendar();
	this.fecha = sdf.parse(calendario.get(Calendar.YEAR)+"-"+calendario.get(Calendar.MONTH)+"-"+calendario.get(Calendar.DAY_OF_MONTH));
         } else {
	this.fecha = sdf.parse(fecha);

         }
      } catch (ParseException e) {
      }

   }

   public String getDescripcion() {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion) {
      this.descripcion = descripcion;
   }

   public int getContador() {
      return this.contador;
   }

   public void setContador(Integer contador) {
      this.contador = contador;
   }

   public Set getCargosAbonos() {
      return this.cargosAbonos;
   }

   public void setCargosAbonos(Set cargosAbonos) {
      this.cargosAbonos = cargosAbonos;
   }

}
