package modelo;
// Generated 01-03-2019 05:54:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private int id;
     private Date fechaInicial;
     private Date fechaFinal;
     private Boolean encurso;
     private Boolean finalizado;
     private Set partidas = new HashSet(0);
     private Set parametros = new HashSet(0);

    public Periodo() {
    }

	
    public Periodo(int id) {
        this.id = id;
    }
    public Periodo(int id, Date fechaInicial, Date fechaFinal, Boolean encurso, Boolean finalizado, Set partidases, Set parametros) {
       this.id = id;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.encurso = encurso;
       this.finalizado = finalizado;
       this.partidas = partidases;
       this.parametros = parametros;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public Boolean getEncurso() {
        return this.encurso;
    }
    
    public void setEncurso(Boolean encurso) {
        this.encurso = encurso;
    }
    public Boolean getFinalizado() {
        return this.finalizado;
    }
    
    public void setFinalizado(Boolean finalizado) {
        this.finalizado = finalizado;
    }
    public Set getPartidas() {
        return this.partidas;
    }
    
    public void setPartidas(Set partidas) {
        this.partidas = partidas;
    }
    public Set getParametros() {
        return this.parametros;
    }
    
    public void setParametros(Set parametros) {
        this.parametros = parametros;
    }




}


